### ISSUE TITLE
GET endpoint for tutor profile

### ISSUE THREAD

**Issue by believemanasseh** [hngi/mobileforce-HomeTeach#88]
- should contain details such as field, interests, price rates, state of origin, description etc. (refer to Figma design for more info)

**Comment by aoluwatooni** [comment]
@hngibot claim

**Comment by aoluwatooni** [comment]
@hngibot claim --force

**Comment by aoluwatooni** [comment]
@Toonie

**Comment by aoluwatooni** [comment]
@believemanasseh I'm on this
